import type { Metadata } from "next";

import "./globals.css";

import { Navbar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
      </head>
      <body className="relative">
        <Navbar />
        {children}
      </body>
      
    </html>
  );
}
